version: 0.2

phases:
  install:
    commands:
        - yum update
        - yum install docker
        - npm install
 
  build:
    commands:
        - echo Build started on `date`
        - echo Compiling the Node.js code...
        - docker build -t skipcart .
 
artifacts:
  files:
    - '**/*'
  discard-paths: yes